### ISSUE TITLE
web_handler Can URL params be accessed in the automation?

### ISSUE THREAD

**Issue by brendann993** [ssieb/custom_components#14]
Hi Ssieb, Is it possible to access url params e.g /setval?value=100 from within the automation linked to web_handler?
Use case is I have a template sensor that I want set the of via the web server e.g not using Home Assistant.
I've been able to increment the value by 1 each time the URL is called but I'd like to be able to set the value to a specific value if possible.
Thanks

**Comment by ssieb** [comment]
The `AsyncWebServerRequest` is available as `request` in a lambda.  See https://github.com/me-no-dev/ESPAsyncWebServer#request-variables for details.

**Comment by brendann993** [comment]
Works perfectly as mentioned
