### ISSUE TITLE
Heapmon (others?) throwing error in ESPhome 2021.10.0-dev

### ISSUE THREAD

**Issue by foxsam21** [ssieb/custom_components#15]
When compiling a yaml with heapmon component in current release everything works as expected but in dev branch is throwing an error.
```
src/esphome/components/heapmon/heapmon.cpp: In member function 'virtual void esphome::debug::HeapMonitor::update()':
src/esphome/components/heapmon/heapmon.cpp:10:24: error: 'ESP' was not declared in this scope
   uint32_t free_heap = ESP.getFreeHeap();
                        ^
```

**Comment by jesserockz** [comment]
`Arduino.h` it's no longer included by default is probably why.

There is a PR open to add heap to the debug component too
