### ISSUE TITLE
Uart_mitm usage question

### ISSUE THREAD

**Issue by ehspill** [ssieb/custom_components#59]
does the uart mitm forward rx and tx or is it one uart pin each?

since hw uarts are limited to three, does each pin/uart has to be seperated?
could we maybe have a way to configure which pin/direction(rx/tx) to use?
could we also have a filter for forwarding, like a string array to not forward if is contained in the uart payload?

**Comment by ssieb** [comment]
Only two uarts are needed.  Data is forwarded both ways.  The pins and direction are part of the uart config.
This was just intended as a simple component to allow sniffing of a uart stream.
