### ISSUE TITLE
Feature Request - Ufire isolated probe interface

### ISSUE THREAD

**Issue by gromyjoe** [ssieb/custom_components#6]
Hi Sam! I found your ezo custom component through LEDgardener.com/forum
I purchased these probes not knowing the code is specific for these devices, is there a possibility of you making a custom component for these? Or do you know of someone that may be able to help? 
Please email me at gromyjoe@gmail.com 
Looking forward to hearing from you

**Comment by ssieb** [comment]
For reference, the code to communicate with them is at https://github.com/u-fire/ISE_Probe.
I don't have time to do this right now and I don't know of anyone else.  You could try asking in the esphome Discord channel.
