### ISSUE TITLE
[Enhancement] HT16K33Alpha multi-display

### ISSUE THREAD

**Issue by docteurzoidberg** [ssieb/custom_components#7]
Actually we can use two components to drive two HT16K33-Alphanumeric displays with different i2c addresses, but we loose the scrolling feature and the refresh isn't sync between devices.

Would be great if we can provide multiple i2c addresses to drive as if it was one larger display.

Technically, can it be done ? I understand that the I2CDevice actually used is only able to speak to one i2c device. Curious about how it could be implemented. 

(I don't know enough about esphome internals to do it, but i can do tests if needed !)

**Comment by ssieb** [comment]
I think I have implemented this, but as usual I have no way to test it. :-)  Let me know if it works.
